"""
Part B: The Editor Agent (With MCP FileSystem)

This agent specializes in synthesizing research notes into
polished, formatted reports and saving them using MCP.

MCP (Model Context Protocol) allows us to connect to external
systems (like file storage) in a standardized way.
"""

import os
import json
from datetime import datetime
from dotenv import load_dotenv
from google.adk.agents import Agent

load_dotenv()

# =============================================================================
# MCP FileSystem Tools
# =============================================================================
#
# In production with a full MCP setup, you would connect to an MCP server:
# 
# from mcp import ClientSession, StdioServerParameters
# 
# mcp_servers=["filesystem-server"]
#
# For this demo, we simulate MCP file operations to show the pattern.

# Output directory for reports
# Using .reports (hidden folder) to prevent ADK from detecting it as an agent
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), ".reports")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def write_file(filename: str, content: str) -> str:
    """
    Write content to a file using MCP FileSystem protocol.
    
    In production, this would be handled by an MCP server.
    The agent calls this tool, and MCP handles the actual file I/O
    securely and consistently across different environments.
    
    Args:
        filename: Name of the file to create (e.g., "report.md")
        content: The content to write to the file.
        
    Returns:
        str: Confirmation message with file path.
    """
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return f"✅ File saved successfully: {filepath}"
    except Exception as e:
        return f"❌ Error saving file: {str(e)}"


def read_file(filename: str) -> str:
    """
    Read content from a file using MCP FileSystem protocol.
    
    Args:
        filename: Name of the file to read.
        
    Returns:
        str: The file contents or an error message.
    """
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return f"❌ File not found: {filename}"
    except Exception as e:
        return f"❌ Error reading file: {str(e)}"


def list_files() -> str:
    """
    List all files in the output directory.
    
    Returns:
        str: JSON list of files with metadata.
    """
    try:
        files = []
        for filename in os.listdir(OUTPUT_DIR):
            filepath = os.path.join(OUTPUT_DIR, filename)
            if os.path.isfile(filepath):
                stat = os.stat(filepath)
                files.append({
                    "name": filename,
                    "size_bytes": stat.st_size,
                    "modified": datetime.fromtimestamp(stat.st_mtime).isoformat()
                })
        
        if not files:
            return "No files found in output directory."
        
        return json.dumps(files, indent=2)
    except Exception as e:
        return f"❌ Error listing files: {str(e)}"


# =============================================================================
# Editor Agent Definition
# =============================================================================

editor_agent = Agent(
    name="Editor",
    model="gemini-2.0-flash",
    instruction="""You are the Editor for the Women Coding Community Tech Scout team.

YOUR ROLE:
- Take raw research notes from the Researcher agent
- Transform them into polished, well-formatted content
- Save the final report using the write_file tool

EDITING PROCESS:
1. Review the research notes provided
2. Organize information logically
3. Write in a clear, engaging style
4. Format as Markdown for readability
5. Save the result to a .md file

OUTPUT FORMAT (Markdown):
```markdown
# [Topic Title]

*Generated by WCC Tech Scout | [Date]*

## Overview
[Brief introduction to the topic]

## Key Findings
[Main discoveries, formatted as bullet points or sections]

## Trends & Insights
[Notable patterns and predictions]

## Resources
[Links and sources for further reading]

---
*Report generated by the WCC Tech Scout multi-agent system*
```

GUIDELINES:
- Write for the WCC community (women in tech, various skill levels)
- Be informative but accessible
- Include practical takeaways when possible
- Always save the final report using write_file

After writing, use write_file to save as 'report.md' or a descriptive filename.
""",
    tools=[write_file, read_file, list_files],
    # In production with MCP:
    # mcp_servers=["filesystem-server"]
)


# =============================================================================
# Standalone Test
# =============================================================================

if __name__ == "__main__":
    # Test the editor independently
    print("📝 Testing Editor Agent...")
    print("=" * 50)
    
    # Sample research notes (simulating input from Researcher)
    sample_research = """
**Research Notes on Agentic AI:**

- **Topic**: Agentic AI and Multi-Agent Systems
- **Key Findings**:
  - Agentic AI refers to AI that can plan, reason, and act autonomously
  - Major companies investing: Google (ADK), OpenAI, Anthropic
  - Multi-agent systems allow specialization and better task handling
- **Trends**:
  - A2A protocol for agent communication
  - MCP for standardized tool access
  - Vertex AI Agent Engine for production deployment
- **Sources**: Google AI Blog, TechCrunch, Official Documentation
"""
    
    print("\n📄 Sample Research Notes:")
    print(sample_research)
    
    # Test the write_file tool
    test_content = """# Agentic AI: The Future of AI Systems

*Generated by WCC Tech Scout | Demo*

## Overview
Agentic AI represents a paradigm shift in how we build AI systems...

## Key Findings
- AI agents can autonomously plan and execute tasks
- Multi-agent systems enable specialization
- New protocols (A2A, MCP) standardize agent interactions

---
*Demo report*
"""
    
    print("\n💾 Testing file write...")
    result = write_file("demo_report.md", test_content)
    print(result)
    
    print("\n📂 Listing files...")
    files = list_files()
    print(files)
    
    print("\n" + "=" * 50)
    print("✅ Editor agent ready for pipeline integration!")
