"""
Part C: Orchestration (A2A Pattern - Sequential Handoff)

This script demonstrates the Agent-to-Agent (A2A) communication pattern
where the Researcher agent passes its findings to the Editor agent.

Pattern: Sequential Handoff
- Researcher finds data
- Passes context to Editor
- Editor writes and saves report

In production, A2A involves network calls between agents that may be
running on different servers or even different organizations. For this
demo, we simulate the logical flow.
"""

import os
from datetime import datetime
from dotenv import load_dotenv

# Import our agents
from researcher import researcher_agent, google_search
from editor import editor_agent, write_file

load_dotenv()


def run_pipeline(topic: str) -> str:
    """
    Run the full Tech Scout pipeline.
    
    This demonstrates the A2A (Agent-to-Agent) pattern:
    1. Researcher agent gathers information
    2. Context is passed to Editor agent
    3. Editor creates and saves the report
    
    Args:
        topic: The topic to research and write about.
        
    Returns:
        str: Status message about the pipeline execution.
    """
    print("\n" + "=" * 60)
    print("🚀 WCC TECH SCOUT PIPELINE")
    print("=" * 60)
    print(f"\n📋 Topic: {topic}")
    print(f"⏰ Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # =========================================================================
    # STEP 1: Research Phase
    # =========================================================================
    print("\n" + "-" * 40)
    print("🕵️ STEP 1: Researcher Agent (TechScout)")
    print("-" * 40)
    print("Using: ADK + Google Search Tool")
    print("Task: Find the latest information...")
    
    # In production with full ADK:
    # from google.adk.runners import Runner
    # researcher_runner = Runner(agent=researcher_agent)
    # research_result = researcher_runner.run(f"Research: {topic}")
    
    # For demo, call the search tool directly
    research_result = google_search(topic)
    
    print("\n📊 Research Results:")
    print(research_result)
    
    # =========================================================================
    # STEP 2: A2A Handoff
    # =========================================================================
    print("\n" + "-" * 40)
    print("🔄 A2A HANDOFF: Researcher → Editor")
    print("-" * 40)
    print("Protocol: Sequential context passing")
    print("Passing research notes to Editor agent...")
    
    # This is where A2A happens - we pass the context from one agent to another
    # In production A2A, this would be a network call with proper authentication
    context_for_editor = f"""
## Research Notes from TechScout

**Topic Requested:** {topic}
**Research Date:** {datetime.now().strftime('%Y-%m-%d')}

{research_result}

---
Please synthesize these notes into a polished blog post and save it.
"""
    
    # =========================================================================
    # STEP 3: Editing Phase
    # =========================================================================
    print("\n" + "-" * 40)
    print("📝 STEP 2: Editor Agent")
    print("-" * 40)
    print("Using: ADK + MCP FileSystem")
    print("Task: Create formatted report and save...")
    
    # In production with full ADK:
    # editor_runner = Runner(agent=editor_agent)
    # edit_result = editor_runner.run(context_for_editor)
    
    # For demo, create the report directly
    report_content = f"""# {topic.title()}: Latest Insights

*Generated by WCC Tech Scout | {datetime.now().strftime('%B %d, %Y')}*

## Overview

This report summarizes the latest developments and trends in {topic}, 
compiled by the WCC Tech Scout multi-agent system.

{research_result}

## Key Takeaways

1. **Stay Current**: The field is evolving rapidly with new tools and protocols
2. **Embrace Standards**: A2A and MCP are becoming industry standards
3. **Start Building**: Hands-on experience is the best way to learn

## Next Steps for WCC Members

- Explore the Google ADK documentation
- Try building your own multi-agent system
- Join the discussion in #ai-learning on Slack

## Resources

- [Google ADK Documentation](https://google.github.io/adk-docs/)
- [A2A Protocol](https://google.github.io/A2A/)
- [Model Context Protocol](https://modelcontextprotocol.io/)
- [Vertex AI Agent Builder](https://cloud.google.com/vertex-ai/docs/agents)

---

*This report was generated by the WCC Tech Scout pipeline:*
*Researcher (TechScout) → A2A Handoff → Editor*

*Built with ❤️ by Women Coding Community*
"""
    
    # Save using MCP FileSystem tool
    filename = f"report_{topic.lower().replace(' ', '_')}.md"
    save_result = write_file(filename, report_content)
    
    print(f"\n💾 Save Result: {save_result}")
    
    # =========================================================================
    # STEP 4: Pipeline Complete
    # =========================================================================
    print("\n" + "=" * 60)
    print("✅ PIPELINE COMPLETE")
    print("=" * 60)
    print(f"\n📄 Report saved as: .reports/{filename}")
    print(f"⏰ Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    return f"Pipeline complete! Report saved to .reports/{filename}"


def run_interactive():
    """Run the pipeline interactively."""
    print("\n" + "=" * 60)
    print("🤖 WCC TECH SCOUT - Interactive Mode")
    print("=" * 60)
    print("\nThis demo shows a 2-agent system:")
    print("  1. Researcher (ADK + Google Search)")
    print("  2. Editor (ADK + MCP FileSystem)")
    print("\nConnected via A2A (Agent-to-Agent) protocol")
    print("-" * 60)
    
    while True:
        print("\n📝 Enter a topic to research (or 'quit' to exit):")
        topic = input("> ").strip()
        
        if topic.lower() in ['quit', 'exit', 'q']:
            print("\n👋 Thanks for using WCC Tech Scout!")
            break
        
        if not topic:
            print("⚠️ Please enter a topic.")
            continue
        
        run_pipeline(topic)


# =============================================================================
# Main Entry Point
# =============================================================================

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        # Run with command line argument
        topic = " ".join(sys.argv[1:])
        run_pipeline(topic)
    else:
        # Run interactively
        run_interactive()
